<a href="https://colab.research.google.com/github/MyriadSpace/Concepts_and_Apps_of_Deep_Learning/blob/main/numpy_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
mat1 = np.ones((3,3))
mat1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
cnt = 1
mat2 = np.zeros((3,3))
for i in range(3):
  for j in range(3):
    mat2[i,j] = mat1[i,j]*cnt
    cnt = cnt + 1
mat2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
mat3 = (mat1 + mat2) * mat2 - mat1/mat2
mat3

array([[ 1.        ,  5.5       , 11.66666667],
       [19.75      , 29.8       , 41.83333333],
       [55.85714286, 71.875     , 89.88888889]])

In [ ]:
mat4 = np.dot(mat2, mat3)
mat4

array([[ 208.07142857,  280.725     ,  365.        ],
       [ 437.89285714,  602.25      ,  795.16666667],
       [ 667.71428571,  923.775     , 1225.33333333]])

In [ ]:
mat5 = np.matmul(mat2, mat3)
mat5

array([[ 208.07142857,  280.725     ,  365.        ],
       [ 437.89285714,  602.25      ,  795.16666667],
       [ 667.71428571,  923.775     , 1225.33333333]])

In [ ]:
vec = np.array([1,2,3])
vec

array([1, 2, 3])

In [ ]:
mat6 = np.dot(mat2, vec)
mat6

array([14., 32., 50.])

In [ ]:
mat7 = np.matmul(mat2, vec)
mat7

array([14., 32., 50.])