<a href="https://colab.research.google.com/github/MyriadSpace/Concepts_and_Apps_of_Deep_Learning/blob/main/tensorflow_exmaple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
mat1 = tf.Variable(tf.ones([3,3], tf.float32))
mat1

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
cnt = 1
mat2 = tf.Variable(tf.zeros((3,3), tf.float32))
for i in range(3):
  for j in range(3):
    mat2[i,j] = mat1[i,j]*cnt
    cnt = cnt + 1
mat2


TypeError: ignored

In [ ]:
import numpy as np
mat_temp = np.array([1,2,3,4,5,6,7,8,9])
mat2 = tf.reshape(mat_temp, [3,3])
mat2 = tf.cast(mat2, tf.float32)
mat2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [ ]:
mat3 = (mat1 + mat2)*mat2 - mat1/mat2
mat3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.      ,  5.5     , 11.666667],
       [19.75    , 29.8     , 41.833332],
       [55.857143, 71.875   , 89.888885]], dtype=float32)>

In [ ]:
mat4 = tf.dot(mat2, mat3)
mat4

AttributeError: ignored

In [ ]:
mat5 = tf.matmul(mat2, mat3)
mat5

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 208.07143,  280.725  ,  365.     ],
       [ 437.89285,  602.25   ,  795.1666 ],
       [ 667.7143 ,  923.775  , 1225.3333 ]], dtype=float32)>

In [ ]:
vec = tf.Variable([1,2,3], dtype=tf.float32)
vec

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
mat6 = tf.dot(mat2, vec)
mat6

AttributeError: ignored

In [ ]:
#vec = tf.expand_dims(vec, axis=1)
#vec = tf.reshape(vec, (3,1))
mat7 = tf.linalg.matvec(mat2, vec)
mat7

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([14., 32., 50.], dtype=float32)>