<a href="https://colab.research.google.com/github/MyriadSpace/Concepts_and_Apps_of_Deep_Learning/blob/main/torch_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch as th
mat1 = th.ones([3, 3], dtype=th.float32)
mat1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
cnt = 1.0
mat2 = th.zeros([3,3], dtype=th.float32)
for i in range(3):
  for j in range(3):
    mat2[i,j] = mat1[i,j]*cnt 
    cnt = cnt + 1
mat2

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
mat3 = (mat1 + mat2)*mat2 - mat1/mat2
mat3

tensor([[ 1.0000,  5.5000, 11.6667],
        [19.7500, 29.8000, 41.8333],
        [55.8571, 71.8750, 89.8889]])

In [ ]:
mat4 = th.dot(mat2, mat3)
mat4

RuntimeError: ignored

In [ ]:
mat5 = th.matmul(mat2, mat3)
mat5

tensor([[ 208.0714,  280.7250,  365.0000],
        [ 437.8929,  602.2500,  795.1666],
        [ 667.7143,  923.7750, 1225.3333]])

In [ ]:
vec = th.tensor([1,2,3], dtype=th.float32)
vec

tensor([1., 2., 3.])

In [ ]:
mat6 = th.dot(mat2, vec)
mat6

RuntimeError: ignored

In [ ]:
mat7 = th.matmul(mat2, vec)
mat7

tensor([14., 32., 50.])